### ISSUE TITLE
Support Listing of Issues Regardless of State

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#10]
The Issues API allows the viewing of either open or closed issues, but not both from the same call. This is silly. We want Issues.find_all(user, repo) to return both open and closed issues; Issues.find_all(user, repo, state) would support limiting by state. Currently, the first invocation assumes `state`=open.

If develop/develop.github.com/#16 is fixed, we'll stop providing a default for `state` and this should just work. Otherwise, we may need to make two calls (one for each state) and merge the results. This would only be done in the absence of a `state` parameter.

**Comment by radar** [comment]
This is now fixed in 4dbfe0c, sorry for the time lag.
