### ISSUE TITLE
Automatically Parse ~/.gitconfig for Credentials

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#15]
If `~/.gitconfig` contains a stanza like the following, and credentials aren't specified in a method call, they should be extracted automatically. 

```
[github]
     user = kate
     token = 545a9a47c1b7bd99cd06c0f812fde717
```

An added benefit of this approach is that applications built upon Octopi don't have to think about credential management; if the user has set up Git correctly, they'll just work, otherwise a rebuke an be issued. ;-)

**Comment by fcoury** [comment]
Seamless authentication using .gitconfig. Closed by b425c53e7556387bf741aefa37e25ef829dccaf5.
