### ISSUE TITLE
Boolean Attributes' Names Should Have '?' Suffix

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#2]
When we generate method names for an object we should use a '?' suffix if the attribute is boolean. For example, a Repository object should have a .fork? and a .private? method. This is not only a better reflection of conventions, it also disambiguates between, in this example, 'fork' being a verb, i.e. a method which causes the repository to be forked, and 'fork' being an attribute, i.e. indicating whether the repository has been forked.

**Comment by fcoury** [comment]
runpaint, can we consider this one closed?
