### ISSUE TITLE
reading commits from a private repo raises error

### ISSUE THREAD

**Issue by brenthargrave** [fcoury/octopi#28]
Gist of the trace: http://gist.github.com/120603
Example of code that yields error: http://gist.github.com/120604

**Comment by radar** [comment]
This is fixed in recent release.

**Comment by radar** [comment]
Real world test for this commited: http://github.com/fcoury/octopi/commit/5973d707c1a1ec0418a26cbafe0fd3b6958066ca

This proves that it works.
