### ISSUE TITLE
Error getting commits from a single private repository

### ISSUE THREAD

**Issue by rodreegez** [fcoury/octopi#29]
When trying to grab a commit from a private repo the following error is raised. This same code works fine if the repo is public. 

Trace: http://gist.github.com/121392
Example: http://gist.github.com/121394

**Comment by radar** [comment]
This is fixed in recent release.

**Comment by radar** [comment]
Proven to be fixed by the real world tests: http://github.com/fcoury/octopi/commit/5973d707c1a1ec0418a26cbafe0fd3b6958066ca
