### ISSUE TITLE
Commit.find raises an error because variable "repo" is not defined

### ISSUE THREAD

**Issue by calavera** [fcoury/octopi#30]
This patch solves the error, I didn't include a test because is an obvious error:

From af1f41ad0a29f36db10672ff8cfa09045d99a240 Mon Sep 17 00:00:00 2001
From: David Calavera david.calavera@gmail.com
Date: Thu, 2 Jul 2009 14:32:05 +0200
Subject: [PATCH] solves Commit.find error

---

 lib/octopi/commit.rb |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/lib/octopi/commit.rb b/lib/octopi/commit.rb
index 863bd31..ff94256 100644
--- a/lib/octopi/commit.rb
+++ b/lib/octopi/commit.rb
@@ -39,9 +39,9 @@ module Octopi
         commit = args.pop
         super "#{commit.repo_identifier}"
       else
-        user, name, sha = *args
-        user, repo, sha = *args
       user = user.login if user.is_a? User
-        name = repo.name  if name.is_a? Repository
-        name = repo.is_a?(Repository) ? repo.name : repo
       self.validate_args(user => :user, name => :repo, sha => :sha)
       super [user, name, sha]
     end
  -- 
  1.6.0.4

**Comment by radar** [comment]
Commit.find now works
