### ISSUE TITLE
Getting Bad URI at random times

### ISSUE THREAD

**Issue by tpitale** [fcoury/octopi#34]
bad URI(is not URI?): /yaml/issues/list/#Octopi::Repository:0x20053ec40/{:state=>"open"}

Keeps popping up at random times. I'd be happy to explore why this might be happening, if someone could point me in the right direction.

**Comment by tpitale** [comment]
not an octopi problem, issue with macruby

**Comment by radar** [comment]
Strange that this happened at all since there's a to_s method in the Repository class.

**Comment by tpitale** [comment]
It's a macruby problem, it's calling the wrong methods because of it's handling of module and inheritence

**Comment by radar** [comment]
Ok, thank you.
