### ISSUE TITLE
files required in wrong order

### ISSUE THREAD

**Issue by branch14** [fcoury/octopi#39]
When I require 'octopi' I get an

  uninitialized constant Octopi::Base (NameError)

since octobi/tag.rb gets require before octopi/base.rb

**Comment by radar** [comment]
Hi branch, sorry for not replying sooner.

What verison of Ruby and operating system are you running on?

**Comment by radar** [comment]
Sort the required files to fix cases such as this ticket (Closed by 897be1cb523027e5c7ac685c419360df05c6f605) [branch14]
