### ISSUE TITLE
Cache API Responses

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#4]
We should be caching the response from GitHub. The implementation for this depends on:
- How we integrate caching into HTTParty, if not there already.
- Whether GitHub returns useful caching metadata, and if not will it?

The logic would have to realise that the format of the data is irrelevant, i.e. if we already have a resource in YAML and the user has requested XML, we hit the cache and reformat the data locally.

In the absence of useful caching metadata, we'd need to hard-code assumptions. For instance the raw blob of a specific commit of a specific file would never change, so a sucessful response could be cached indefinitely.

**Comment by runpaint** [comment]
https://gist.github.com/98030/4374b7a669e59703601675382a37512de453f87c looks hopeful.

**Comment by radar** [comment]
This also looks helpful: http://github.com/newbamboo/api_cache/tree/master

**Comment by radar** [comment]
Using APICache to do this, my fork anyway.
