### ISSUE TITLE
Installing gem from Gemcutter fails

### ISSUE THREAD

**Issue by mcmire** [fcoury/octopi#42]
According to Gemcutter (which claims octopi is up to 0.2.6), octopi depends on mechanize >= 0.9.8. However, the latest version of mechanize is only 0.9.3, so installing fails. Forcing installation of 0.2.5 instead works.

**Comment by radar** [comment]
Ah, my bad. Fixed.

**Comment by mcmire** [comment]
Thanks!

**Comment by radar** [comment]
Beautiful, thanks for that!
