### ISSUE TITLE
No access to github resource!?

### ISSUE THREAD

**Issue by kristianmandrup** [fcoury/octopi#47]
<pre>
    desc "delete NAME", "delete public repository NAME from your github account"    
    def delete(name)
      authenticated do                 
        user = Api.api.user      
        puts "user:" + user.inspect        
        repository = user.repositories.find(name)                              
        puts "repo:" + repository.inspect        
        say "Repository #{name} was deleted successfully" if repository.delete!
      end
    end 

    desc "collaborators NAME", "list all collaborators for repository NAME"    
    def collaborators(name)  
      user = Api.api.user
      repository = user.repositories.find(name)      
      result = repository.collaborators
      puts result.inspect
    end
</pre>

I get the error below for all other tasks using this kind of recipe (issues, branches, tags...). 
What am I doing wrong?
I am able to perform the delete! (with no effect) with the same tactic !?

I can see that the user and repo objects when doing the delete are as expected :)

<pre>
kristian-mandrups-macbook-pro:lib kristianconsult$ thor github:repo:delete cool_stuff
W, [2010-04-05T16:11:26.188454 #28728]  WARN -- : Using in memory store

user:#<Octopi::User:0x0000010281b4c0 @gravatar_id="2a018f8b16a3fe7273afde907c2e1bec", @created_at=2009-09-09 13:49:19 -0400, @public_gist_count=27, @public_repo_count=60, @following_count=3, @id=125005, @followers_count=5, @login="kristianmandrup", @plan=#<Octopi::Plan:0x0000010281b3e0 @name="free", @collaborators=0, @space=307200, @private_repos=0>, @collaborators=0, @disk_usage=29781, @private_gist_count=3, @owned_private_repo_count=0, @total_private_repo_count=0>

repo:#<Octopi::Repository:0x00000100849e88 @forks=0, @watchers=1, @fork=false, @url="http://github.com/kristianmandrup/cool_stuff", @private=false, @name="cool_stuff", @owner=#<Octopi::User:0x000001015e2078 @gravatar_id="2a018f8b16a3fe7273afde907c2e1bec", @created_at=2009-09-09 13:49:19 -0400, @public_gist_count=27, @public_repo_count=60, @following_count=3, @id=125005, @followers_count=5, @login="kristianmandrup", @plan=#<Octopi::Plan:0x000001015e1f98 @name="free", @collaborators=0, @space=307200, @private_repos=0>, @collaborators=0, @disk_usage=29781, @private_gist_count=3, @owned_private_repo_count=0, @total_private_repo_count=0>, @open_issues=0>
Repository cool_stuff was deleted successfully

kristian-mandrups-macbook-pro:lib kristianconsult$ thor github:repo:collaborators cool_stuff
W, [2010-04-05T16:11:58.805560 #28903]  WARN -- : Using in memory store
GitHub returned status 403. Retrying request.
/Users/kristianconsult/.rvm/gems/ruby-1.9.1-p378/gems/octopi-0.2.8/lib/octopi/api.rb:129:in `rescue in get': Github returned status 403, you may not have access to this resource. (Octopi::APIError)
</pre>

Thanks!

**Comment by radar** [comment]
Seems here that you need to be authenticated for a collaborators request.

**Comment by radar** [comment]
Fixed.
