### ISSUE TITLE
Explicit Authentication example is wrong

### ISSUE THREAD

**Issue by jeffWelling** [fcoury/octopi#59]
The example of Explicit Authentication number 1 is wrong, trying this code in irb shows;
http://pastie.org/1841919

**Comment by radar** [comment]
Are you able to submit a patch to fix this issue? I think it should be `repo.issues.create`.

**Comment by nithinbekal** [comment]
Shouldn't it be like this:

```
authenticated_with :login => 'nithinbekal', :token => '...' do
  repo = Repository.find(name:'test', user:'nithinbekal')
  issue = Issue.open :repo => repo, 
    :params => {:title=> "fake ticket", :body=> "This issue was opened with octopi"}
  puts issue.number
end
```

That worked when I tried to open an issue on one of my repositories.

**Comment by radar** [comment]
@nithinbekal: Are you able to submit a pull request with that fix then please? Just mainly so I can attribute it easily to you :) Thanks!

**Comment by nithinbekal** [comment]
@radar Done! :)

**Comment by radar** [comment]
Thank you!! <3
