### ISSUE TITLE
Validate User Names, Repository Names, and SHAs

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#6]
Valid user names, repository names, and SHAs match a regex, so we should check for bad data and raise a useful exception if we see it.

**Comment by runpaint** [comment]
May be fixed by commit 9fbc19ce4f897e9f7b787d910ed66d84dcc18682 . Leaving for fcoury to review.

**Comment by fcoury** [comment]
Closed by http://github.com/fcoury/octopi/commit/9fbc19ce4f897e9f7b787d910ed66d84dcc18682
