### ISSUE TITLE
No way of accessing an comments of an Issue?

### ISSUE THREAD

**Issue by jeffWelling** [fcoury/octopi#60]
I've spent all day looking for a way to retrieve the comments on an Issue, but I can't find anything.
Doesn't Octopi have a way of getting the comments as well as the Issue itself? 
What's the point otherwise... 
I must be missing it somewhere, can someone point it out to me if I am?

**Comment by radar** [comment]
You're correct: it doesn't have a way to do this at the moment.

brb, working magic.

**Comment by radar** [comment]
The 0.4.1 release contains this fix. Let me know if there's anything else you find broken.

**Comment by jeffWelling** [comment]
Thanks!!!

**Comment by jeffWelling** [comment]
Hey thanks for making comments available.  I was wondering though, could you make any more comment attributes available, like created_at or updated_at ?

**Comment by radar** [comment]
Done, released as 0.4.2.

**Comment by jeffWelling** [comment]
Your my hero :D
A HUGE thank you for being around to fix it within minutes!!!
