### ISSUE TITLE
commit details not supported as per README

### ISSUE THREAD

**Issue by gregwebs** [fcoury/octopi#70]
repo.commits.first.details
NoMethodError: undefined method `details' for #Octopi::Commit:0x000000017a2af0

**Comment by radar** [comment]
I can confirm this bug but I haven't gone as far as to investigate why / how it's happening. Would you be able to do that and submit a pull request with any fix that's necessary? Thanks!

**Comment by gregwebs** [comment]
The pull would be to delete that example from the README. I thought I would
open this ticket instead in case you wanted to attempt some archaeology if
you had an idea of where this functionality was deleted (assuming it worked
at some point).

**Comment by radar** [comment]
It would be happening because the GitHub API doesn't return details in commit collections any more. Instead, you have to find the individual commit you want the details for and then do a query on that. I've updated the README in effect.
