### ISSUE TITLE
Date Attribues Should be Date Objects

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#9]
Attributes that have dates as values should be coerced into a date object so objects of the same type can be compared with respect to their date. For instance, Issue objects have .created_at and .updated_at.

**Comment by radar** [comment]
Hi, I have a branch of this project and I am coercing them into Time objects. I'm going to be submitting a pull request in a couple of days when I wrap everything up.

**Comment by radar** [comment]
Date objects are now date objects. Let me know if you find a situation where they are not.
